apiVersion: v1
kind: Service
metadata:
  name: langfactsservice-helm
  labels:
    k8s-app: langfactsservice-helm
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: langfacts-helm